Fix linters and make review changes
chimwemwe007/blog-app pull request #9
Opened 2022-11-05 13:26 UTC by chimwemwe007

# Blog app - Add forms

### the following has bbeen accomplished in this pull request.

- create a method called current_user in your ApplicationController to make current user data available to all controllers.
- It will return the first user from the database.
- Don't worry about proper authentication at this time. You will add it in the upcoming projects.
- Create forms to perform the following functions:
- Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
- Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
- Allow Users to add likes to Posts.

2022-11-05 14:06 UTC, jaflih requested changes
Hi @chimwemwe007 , 

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

2022-11-05 14:06 UTC, jaflih commented on app/controllers/posts_controller.rb
> +    end
You have a bug in your project when I create a new post

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/7243132/200123583-031d35cb-9520-42d2-91e3-f961f4e4cf03.png">


**Follow my others comments to correct it.**

2022-11-05 14:06 UTC, jaflih commented on db/migrate/20221025191034_create_users.rb
>        t.integer :posts_counter
Please correct this line like this to remove the bug

` t.integer :posts_counter, default: 0`

2022-11-05 14:06 UTC, jaflih commented on db/migrate/20221025191732_create_posts.rb
>        t.integer :comments_counter
Please correct this line like this to remove the bug

`t.integer :comments_counter, default: 0`

2022-11-05 14:06 UTC, jaflih commented on db/migrate/20221025191732_create_posts.rb
>        t.integer :likes_counter
Please correct this line like this to remove the bug

`t.integer :likes_counter, default: 0`

2022-11-05 14:31 UTC, chimwemwe007 commented
The other branch was deleted due to technical issues, and i accidentally re-submitted the deleted branch link.

2022-11-05 15:33 UTC, FrederickMih approved these changes
# Status: Approved :heavy_check_mark: 


Hi @chimwemwe007 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


![](https://media.giphy.com/media/3o72FcJmLzIdYJdmDe/giphy.gif)

## Highlights

- Great communication with reviewers :heavy_check_mark: 
- Correct Gitflow has been followed :heavy_check_mark: 
- No Linter error :heavy_check_mark: 

## Optional suggestions

- [**Optional**] The title(Fix linters and make review changes) of your PR is really poor. It basically says nothing concerning what you are implementing(Blog app - add forms)
- You were told to include all the commands necessary to run your app locally but you didn't. Would you fix it? This way your README.md file will be really interesting and descriptive.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-05 15:33 UTC, FrederickMih commented on db/seeds.rb
> +AJANLEKOKO ARIBIDESI
- [**Optional**] This uninitialized constant prevented us from running the command `rails db:seed` hence we could only create the user, post, and comment manually using the rails console. Let's kindly fix :wrench: the bug :bug: Below is the screenshot of the error on my console: 

![Screenshot from 2022-11-05 16-08-40](https://user-images.githubusercontent.com/63087491/200126711-9432c5e9-3fa3-4f17-91c7-fb2b4cdf2b63.png)

2022-11-05 15:33 UTC, FrederickMih commented on app/views/posts/_add_comment.html.erb
> +</div>
- [**Optional**] With Rails, we have a unique default way of organizing our work hence, this form could have been created in the path **views/comments/new.html.erb**. This is really important, especially when scaling or debugging our work in the future.

2022-11-06 12:16 UTC, merged

2024-01-27 15:19 UTC, Reem-lab reviewed
# Hi @chimwemwe007,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ]  Descriptive PR⭐
- [ ]  No Linters error 🤩
- [ ] Good job working on the forms💪🏻
- [ ] Good job working on the routes 🙏🏻



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._